version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${ODOO_CONTAINER_NAME}
    ports:
      - "${ODOO_PORT}:8069"
      - "${DEBUGPY_PORT}:8888"
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - odoo_server:/usr/lib/python3/dist-packages/odoo
      - addons_data:/mnt/extra-addons
    env_file:
      - stack.env

  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdb-data:/var/lib/postgresql/data/pgdata
    env_file:
      - stack.env

volumes:
  odoo-web-data:
  pgdb-data:
  odoo_server:
  addons_data:
