services:
  web:
    container_name: odoo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo_server:/usr/lib/python3/dist-packages/odoo
      - addons_data:/mnt/extra-addons
    entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf

  db:
    container_name: pgdb
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=openpgpwd
      - POSTGRES_USER=openpg
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdb-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  pgdb-data:
  odoo_server:
  addons_data:
